default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ruby
  password: password
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: beta_blog_development

test:
  <<: *default
  database: beta_blog_test

production:
  <<: *default
  database: beta_blog_production
